let dataArr = [
    {
      "site_name": "AT1",
      "site_label": "An Thanh 1",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "AT2",
      "site_label": "An Thanh 2",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "AT3",
      "site_label": "An Thanh 3",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "AT4",
      "site_label": "An Thanh 4",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "AT5",
      "site_label": "An Thanh 5",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "GL1",
      "site_label": "Gia Lai 1",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "GL2",
      "site_label": "Gia Lai 2",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "GL3",
      "site_label": "Gia Lai 3",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "GL4",
      "site_label": "Gia Lai 4",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "HA1",
      "site_label": "Hoàng Anh 1",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "HA2",
      "site_label": "Hoàng Anh 2",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "HA3",
      "site_label": "Hoàng Anh 3",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "HA4",
      "site_label": "Hoàng Anh 4",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "KimPack",
      "site_label": "KimPack",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "MDF",
      "site_label": "MDF",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "ST",
      "site_label": "Siêu Thành",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "ST1",
      "site_label": "Sơn Thành 1",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "ST2",
      "site_label": "Sơn Thành 2",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "ST3",
      "site_label": "Sơn Thành 3",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "STg1",
      "site_label": "Sơn Thượng",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "STr1",
      "site_label": "Sơn Trung",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "STy",
      "site_label": "Sơn Thủy",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "TB1",
      "site_label": "Thăng Bình 1",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "TB2",
      "site_label": "Thăng Bình 2",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "TB3",
      "site_label": "Thăng Bình 3",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "TH1",
      "site_label": "Tân Hội 1",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "TH2",
      "site_label": "Tân Hội 2",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "TH3",
      "site_label": "Tân Hội 3",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    },
    {
      "site_name": "TH4",
      "site_label": "Tân Hội 4",
      "grafana_id": null,
      "grafana_dashboard_site": null,
      "startup_status": null,
      "last_power_hourly": null,
      "last_accumulate_power_hourly": null,
      "last_time_hourly": null,
      "present_power_hourly": null,
      "startup_at": null
    }
  ]

module.exports = dataArr